services:
  app:
    build: .
    volumes:
      - ${APP_VOLUME_PATH}/logs:/code/logs
      - ${APP_VOLUME_PATH}/.env:/code/.env
      - ${APP_VOLUME_PATH}/overfast-crontab:/etc/crontabs/root
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8080 || exit 1"]
      start_period: 20s
      timeout: 10s

  redis:
    image: "redis:alpine"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APP_VOLUME_PATH}/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
      timeout: 10s

  nginx:
    build:
      context: ./scripts/nginx
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app
      - redis
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      start_period: 10s
      timeout: 10s