name: "Pytest"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Pytest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: [1.2.2]

    steps:
    - name: Build project
      uses: TeKrop/install-python-poetry-project@v3
      with:
        python-version: ${{ matrix.python-version }}
        poetry-version: ${{ matrix.poetry-version }}

    - name: Run tests
      run: |
        PYTHONPATH=app/ python -m pytest -v --cov-fail-under=80 --cov-report=html --cov=app/ tests/
        PERCENT=$(cat htmlcov/index.html | grep "pc_cov" | awk -F '>' '{print $2}' | awk -F '%' '{print $1}')
        echo "COVERAGE=$PERCENT" >> $GITHUB_ENV

    - name: Update test coverage badge
      if: github.event_name == 'push'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 1362ebafcd51d3f65dae7935b1d322eb
        filename: pytest.json
        label: coverage
        message: ${{ env.COVERAGE }}%
        minColorRange: 50
        maxColorRange: 90
        valColorRange: ${{ env.COVERAGE }}